### ISSUE TITLE
Implement our own Comsos Client

### ISSUE THREAD

**Issue by Buckram123** [SeedyROM/croncat-rs#22]
`cosm-orc` was enough for most of the tasks, but it's time to create our client.
Main reasons:
- `CosmOrc` doing runtime block in most of it's methods. And we have alot of async stuff.
- We can't extend it, unless we fork it. For example: we can't view account's native balance or #19
- It was designed for testing and profiling gas

Here is the example how it went wrong:
https://github.com/CronCats/croncat-rs/blob/42ef5ad2b40c36f6ca975e13d2307e50e1327375/croncat/src/streams/tasks.rs#L37

1. Because it blocks runtime inside `query`/`execute` we have to spawn a new runtime https://github.com/CronCats/croncat-rs/blob/42ef5ad2b40c36f6ca975e13d2307e50e1327375/croncat/src/streams/tasks.rs#L53
2. Because it can't query balances - the best we can get is https://github.com/CronCats/croncat-rs/blob/42ef5ad2b40c36f6ca975e13d2307e50e1327375/croncat/src/streams/tasks.rs#L61-L65
3. Because it takes mutable reference(for profiling gas, which we don't need for light agent client btw) - we need to "copy" it, but it doesn't implement `Clone`/`Copy` so we have to re-initialize it every cycle https://github.com/CronCats/croncat-rs/blob/42ef5ad2b40c36f6ca975e13d2307e50e1327375/croncat/src/streams/tasks.rs#L48-L50

So IMO we should create client that we can modify and pretty sure we want lighter version.

**Comment by de-husk** [comment]
Hey! Cosm-orc author here who just happened to see this. 

Thanks for writing all of this up 🙏 

Definitely sounds like you should make your own wrapper around [cosm-rs](https://github.com/cosmos/cosmos-rust) or maybe [ocular](https://github.com/PeggyJV/ocular) since cosm-orc doesnt fit your needs, but Im going to fix the points you brought up where relevant:

> 1.  Because it blocks runtime inside query/execute we have to spawn a new runtime

Great point, I was planning on exposing an async version of the API. I made an issue to track.

> 2. Because it can't query balances - the best we can get is

Yeah, cosm-orc is just meant to be used for smart contract operations. General cosmos sdk queries are not in scope right now.

> 3. Because it takes mutable reference(for profiling gas, which we don't need for light agent client btw) - we need to "copy" it.

Great point about not implementing Clone. Made an issue. More generally speaking, Im going to make the non-gas profiling use case a bit easier to use. 

Thanks again for the feedback.

**Comment by Buckram123** [comment]
Hey, @de-husk! Thanks for the cool tool that gave us the opportunity to try cosmwasm operations from the rust app
We will use it for gas profiling in our smart contract later. Saw your tests for DA0-DA0, that's a great example of using it for this purpose.
