### ISSUE TITLE
Add polling fallback to websocket connection

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#35]
Currently we're connecting to websockets, but we're finding out that it's not as reliable as we'd hoped.

We need to make sure the websocket connection doesn't silently drop, causing the agent to not know about new blocks. The solution isn't going to be pretty, but we basically need a basic system that will check when the last block came in, and make sure we manually poll the RPC if we do not receive a block after X seconds.

The X seconds can be a setting in the config files, I believe, since block times will vary across blockchains/networks.

For instance, in Juno, the block times are around 6 seconds. So perhaps 30 blocks come in successfully and then the websocket connection fails. We'll want to have a timer that checks, for instance, every 7 seconds to ensure a new block has come in. (This could be done simply by keeping track of the last block height the 7-second loop knows about and making sure it's changed.)

In our example, if 7 seconds has passed and we still have the same block height, we need to manually ping the RPC (and all the logic that is usually executed when a new block comes in) instead of waiting for websockets. We can also attempt to reconnect to websockets at this time as well.

**Comment by SeedyROM** [comment]
So there's a few problems with your solution, relying on block times being constant (7s~) is a huge problem. Not only because they're not 100% reliable, but because there's also connection/transmit latency for RPC requests. You could get out of sync in all sorts of horrible ways (for instance sending an RPC request immediately after a block was processed, aka a single/multi block lag). I'm sure @TrevorJTClarke and I have seen similar bugs caused by having hardcoded intervals for block duration or a sloppy fallback handler.

**Take these all with a grain of salt, I'm just sharing ideas**

## Ideas

### Idea 1:
Have the websocket connection periodically reload if it fails, and at the same time call RPC to get the blocks it's missed at a much smaller interval. Let's say 250/500ms? You could also overshoot the blocks required and say get the next N blocks that don't exist. You could also have a list of fallback nodes when you lose connection to a single source of truth. However that's another can of worms.

### Idea 2:
Have our own specified ping routine to check the socket is still active instead of the protocol level one, Also with some sort of back off interval to handle ddosing nodes.

### Idea 3:
Keep two open websocket connections, trade them off when one is checking the other for still existing and fallback to RPC if they've both died. You could also chose other nodes roundrobin like I specified above and use a sane interval to pick up the loss.

What do you think @TrevorJTClarke @mikedotexe?

I think idea 3 might be the best solution for sanity and reliability.

**Comment by SeedyROM** [comment]
Also we have to account for a node completely going offline, is this something anybody else has considered for the edge cases?

**Comment by TrevorJTClarke** [comment]
> Also we have to account for a node completely going offline, is this something anybody else has considered for the edge cases?

Yeah, so since this is an "Agent" rather than an indexer, the guarantees are much different.
An agent can go offline, and then just get removed from the active agent queue without issue. Whenever the agent comes back, theres only the need to check back in & become active. This keeps the node logic simple

**Comment by TrevorJTClarke** [comment]
> Keep two open websocket connections, trade them off when one is checking the other for still existing and fallback to RPC if they've both died.

Thats a very interesting idea -- I was actually thinking of something similar for just polling.

An agent that doesnt run its own RPC node, will need to connect to publicly accessible RPC nodes.

So I would love the agent to connect / configure multiple RPC nodes, and either roundrobin or just have solid fallback rotation.
If thats possible with WS too, great!
